"""upgrade_artifacts_user_scoped

Revision ID: 1f27938e875e
Revises: 7508176c3c82
Create Date: 2026-04-28 06:23:11.638634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f27938e875e'
down_revision: Union[str, Sequence[str], None] = '7508176c3c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Add new columns as NULLABLE
    op.add_column(
        "artifacts",
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("user_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("session_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("mime_type", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "artifacts",
        sa.Column("file_size", sa.Integer(), nullable=True),
    )

    # 2️⃣ Backfill existing rows (SAFE DEFAULTS)
    # Adjust these values if you want different legacy semantics
    op.execute("""
        UPDATE artifacts
        SET
            tenant_id = 'default_tenant',
            user_id = 'system',
            session_id = 'legacy'
        WHERE tenant_id IS NULL
    """)

    # 3️⃣ Enforce NOT NULL constraints
    op.alter_column("artifacts", "tenant_id", nullable=False)
    op.alter_column("artifacts", "user_id", nullable=False)
    op.alter_column("artifacts", "session_id", nullable=False)

    # 4️⃣ Add useful indexes
    op.create_index("ix_artifacts_tenant_id", "artifacts", ["tenant_id"])
    op.create_index("ix_artifacts_user_id", "artifacts", ["user_id"])
    op.create_index("ix_artifacts_session_id", "artifacts", ["session_id"])
    op.create_index("ix_artifacts_file_id", "artifacts", ["file_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
