"""add path column to artifact

Revision ID: 7508176c3c82
Revises: 
Create Date: 2026-02-26 09:20:43.746219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7508176c3c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_users')
    op.add_column('artifacts', sa.Column('path', sa.String(length=500), nullable=True))

    op.execute("UPDATE artifacts SET path='/legacy' WHERE path IS NULL")

    op.alter_column('artifacts','path',nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'path')
    op.create_table('test_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_users_pkey'))
    )
    # ### end Alembic commands ###
